client:
  url: http://gf_loki:3100/loki/api/v1/push

limits_config:
  readline_rate_enabled: true
  readline_rate: 1000
  readline_burst: 1000
  readline_rate_drop: false

target_config:
  sync_period: "5s"

scrape_configs:
  - job_name: test
    pipeline_stages:
      - json:
          expressions:
            protocol: protocol
            status: status
            bytes: bytes
            referer: referer
          source:
      - labels:
          status: status
          host: sp20
          type: file
      - timestamp:
          source: datetime
          format: UnixNs
      - output:
          source: output
    static_configs:
    - targets:
         - localhost
      labels:
         __path__: /log/error.log
